### HMM

In [2]:
! pip install -q hmmlearn

In [3]:
# import the necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm

In [14]:
states = ['start', '1', '2', '3', '4', 'end']
n_states = len(states)
print('Number of hidden states :',n_states)
# Define the observation space
observations = ['T', 'A', 'G', 'A']
n_observations = len(observations)
print('Number of observations :',n_observations)

Number of hidden states : 6
Number of observations : 4


In [29]:
start_probability = np.array([1., 0, 0, 0, 0, 0])
print("State probability: ", start_probability)
transition_probability = np.array([
    [0, 0.5, 0.5, 0, 0, 0],    # from start
    [0, 0.2, 0, 0.8, 0, 0],    # from 1
    [0, 0, 0.8, 0, 0.2, 0],    # from 2
    [0, 0, 0, 0.4, 0, 0.6],    # from 3
    [0, 0, 0, 0, 0.1, 0.9],    # from 4
    [0, 0, 0, 0, 0, 0]         # from end
])
print("\nTransition probability:\n", transition_probability)
emission_probability = np.array([
    [0, 0 , 0 , 0],
    [0.4, 0.1, 0.2, 0.3],    # state 1 emissions
    [0.4, 0.1, 0.1, 0.4],    # state 2 emissions
    [0.2, 0.3, 0.3, 0.2],    # state 3 emissions
    [0.1, 0.4, 0.4, 0.1],    # state 4 emissions
    [0, 0, 0, 0]
])

State probability:  [1. 0. 0. 0. 0. 0.]

Transition probability:
 [[0.  0.5 0.5 0.  0.  0. ]
 [0.  0.2 0.  0.8 0.  0. ]
 [0.  0.  0.8 0.  0.2 0. ]
 [0.  0.  0.  0.4 0.  0.6]
 [0.  0.  0.  0.  0.1 0.9]
 [0.  0.  0.  0.  0.  0. ]]


In [30]:
model = hmm.CategoricalHMM(n_components=4)
model.startprob_ = start_probability
model.transmat_ = transition_probability
model.emissionprob_ = emission_probability

In [31]:
n_states

6

In [32]:
observations_sequence = np.array([observations.index(obs) for obs in ['T', 'A', 'G', 'A']]).reshape(-1, 1)
observations_sequence

array([[0],
       [1],
       [2],
       [1]])

In [33]:
# Predict the most likely sequence of hidden states
hidden_states = model.predict(observations_sequence)
print("Most likely hidden states:", hidden_states)

ValueError: startprob_ must have length n_components

In [ ]:
log_probability, hidden_states = model.decode(observations_sequence,
											lengths = len(observations_sequence),
											algorithm ='viterbi' )

print('Log Probability :',log_probability)
print("Most likely hidden states:", hidden_states)

In [ ]:
# Plot the results
sns.set_style("whitegrid")
plt.plot(hidden_states, '-o', label="Hidden State")
plt.xlabel('Time step')
plt.ylabel('Most Likely Hidden State')
plt.title("Sunny or Rainy")
plt.legend()
plt.show()
